In [1]:
import numpy as np 
import os

In [ ]:
def adding_new_edge_to_graph(graph, elem):
    graph.append([int(elem)])
    print(graph)

In [ ]:
graph=[]
dirname = os.getcwd()
filename = os.path.join(dirname,'hits_input.txt')
with open(filename,'r') as f:
    line = f.readline()
    no_of_pages=int(line)
    line = f.readline()
    while no_of_pages:
        elem = line.split()
        adding_new_edge_to_graph(graph, elem)
        line = f.readline()
        no_of_pages-=1

In [11]:
threshold=0.0001
k=0
no_of_pages=6                                       
graph = [[0, 1, 1, 1, 0, 1],[1, 0, 1, 0, 0, 1],[0, 1, 0, 1, 1, 0],[0, 1, 1, 0, 0, 0],[1, 1, 1, 1, 1, 1],[1, 0, 1, 0, 1, 0]]
hubs=np.ones(no_of_pages,dtype = float)
prevhubs=np.ones(no_of_pages,dtype = float)
authorities=np.zeros(no_of_pages,dtype = float)
print(hubs)
print(graph)
error=no_of_pages
MSE1=no_of_pages
MSE2=no_of_pages
while MSE1+MSE2>threshold:
    print("\n\nIteraton Number: " + str(k+1) + ".................................................")
    sum_authorities=0
    prev_authority=authorities.copy()
    for i in range(0,no_of_pages):
        authorities[i]=0
        for j in range(0,no_of_pages):
            if(graph[j][i]==1):
                authorities[i]=authorities[i]+hubs[j]
        sum_authorities=sum_authorities+authorities[i]
    authorities=authorities/sum_authorities
    print(authorities)

    sum_hubs=0
    prevhubs=hubs.copy()
    print(prevhubs)
    for i in range(0,no_of_pages):
        hubs[i]=0
        for j in range(0,no_of_pages):
            if(graph[i][j]==1):
                hubs[i]=hubs[i]+authorities[j]
        sum_hubs=sum_hubs+hubs[i]

    hubs=hubs/sum_hubs
    print(hubs)
#     error=0.0
#     for i in range(0,no_of_pages):
#         error=error+abs(prevhubs[i]-hubs[i])
    MSE1 = np.square(np.subtract(prevhubs,hubs)).mean()
    MSE2 = np.square(np.subtract(prev_authority,authorities)).mean()
    print(MSE1+MSE2)
    k=k+1

[1. 1. 1. 1. 1. 1.]
[[0, 1, 1, 1, 0, 1], [1, 0, 1, 0, 0, 1], [0, 1, 0, 1, 1, 0], [0, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1], [1, 0, 1, 0, 1, 0]]


Iteraton Number: 1.................................................
[0.14285714 0.19047619 0.23809524 0.14285714 0.14285714 0.14285714]
[1. 1. 1. 1. 1. 1.]
[0.19480519 0.14285714 0.12987013 0.11688312 0.27272727 0.14285714]
0.7263794406651549


Iteraton Number: 2.................................................
[0.14333333 0.18333333 0.22333333 0.15333333 0.14       0.15666667]
[0.19480519 0.14285714 0.12987013 0.11688312 0.27272727 0.14285714]
[0.19742883 0.14416896 0.13131313 0.11202938 0.27548209 0.13957759]
0.00010506126278489823


Iteraton Number: 3.................................................
[0.14295775 0.18309859 0.22206573 0.15446009 0.13967136 0.15774648]
[0.19742883 0.14416896 0.13131313 0.11202938 0.27548209 0.13957759]
[0.19777375 0.14412374 0.13156873 0.11170075 0.27569247 0.13914056]
8.126959732099812e-07
